//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puestos
    {
        public Puestos()
        {
            this.Empleados = new HashSet<Empleados>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string NivelRiesgo { get; set; }
        public Nullable<double> SalarioMaximo { get; set; }
        public Nullable<double> SalarioMinimo { get; set; }
    
        public virtual ICollection<Empleados> Empleados { get; set; }
    }
}
